m

diff --git a/bin/mapreduce b/bin/mapreduce
--- a/bin/mapreduce
+++ b/bin/mapreduce
@@ -8,33 +8,17 @@ WORKER1_LOG="$LOG_DIR/worker-6001.log"
 WORKER2_LOG="$LOG_DIR/worker-6002.log"
 
 
-check_status() {
-    local manager=0
-    local worker=0
-
-    if pgrep -f mapreduce-manager > /dev/null; then
-        manager=1
-    fi
-
-    if pgrep -f mapreduce-worker > /dev/null; then
-        worker=1
-    fi
-
-    echo $(( manager | (worker << 1) ))
-}
-
-
-
 start_server () {
-    
-    local status
-    status=$(check_status)
+    if pgrep -f mapreduce-manager &> /dev/null; then
+            echo "Error: mapreduce-manager is already running"
+            exit 1
+        fi
+        if pgrep -f mapreduce-worker &> /dev/null; then
+            echo "Error: mapreduce-worker is already running"
+            exit 1
+        fi
 
-    if [ "$status" -ne 0 ]; then
-        echo "Error: Some components are already running."
-        exit 1
-    fi
-
+    echo "starting mapreduce ..."
     mkdir -p var/log
     rm -f var/log/manager.log var/log/worker-6002.log var/log/worker-6001.log
     mapreduce-manager --host localhost --port 6000 --logfile var/log/manager.log &
@@ -97,5 +81,6 @@ elif [ $1 == "stop" ]; then
 elif [ $1 == "status" ]; then
     status_server
 elif [ $1 == "restart" ]; then
-    restart_server
+    stop_server
+    start_server
 fi
